### ISSUE TITLE
Conferences need an update

### ISSUE THREAD

**Issue by dveeden** [shlomi-noach/awesome-mysql#120]
It is not called "MySQL Central" anymore. It is called the "MySQL and HeatWave Summit"

https://www.mysql.com/news-and-events/events/mysql-summit-2024.html

**Comment by dveeden** [comment]
Possible addition: https://www.pingcap.com/htap-summit/ but not sure if that's allowed?

**Comment by shlomi-noach** [comment]
Yeah, I wonder if we should remove the conferences section altogether? I think it was wrong to enlist confierences in an OSS-oriented list. HTAP summit looks very interesting as a database conference, but I think it does not revolve around MySQL specifically? And it's a great example, because it's again super interesting and why not include it, but open up the question of why not including any conference that has to do with databases in the first place.

**Comment by dveeden** [comment]
Some issues I see with listing conferences:

1. Keeping it up to date. Especially if would include meetups etc.
2. Separation between open source (FOSDEM, etc) and commercial events (AWS Summit)
3. Percentage of conference that is MySQL and/or Database specific.
4. Types of events: Conferences, Meetups, Webinars, etc

So might be best to remove it for now.
