### ISSUE TITLE
Connectors section needs to be checked.

### ISSUE THREAD

**Issue by dveeden** [shlomi-noach/awesome-mysql#44]
- Looks like Connector/J and DBD::mysql are missing.
- http://www.libattachsql.org/ seems to be a dead. (the web page, don't know about the project)
- There is an [official Connector/Node.js](https://dev.mysql.com/downloads/connector/nodejs/) connector. Should we list both connectors?
- Should we add libmysqlclient? (or Connector/C as https://dev.mysql.com/downloads/connector/ calls it)
- MariaDB also has a Connector/C... 
- https://sourceforge.net/projects/mysql-python/ links to github and there the README states that it is a legacy version. We should consider removing it in favor of Connector/J

**Comment by dveeden** [comment]
@linuxjedi What is the status of the libattachsql project and website?

**Comment by LinuxJedi** [comment]
Unfortunately I haven't been able to do any development work on libattachsql since I left HP. 1.0 should work quite well but the API isn't great, 2.0 is unfinished. I can't see my circumstances changing enough for that situation to change any time soon.

I let the domain lapse recently so the website will be down (the source for the site is still on GitHub).

There has been recent interest but it needs someone to commit time and resources to it.

I would also look at libdrizzle, especially the redux versions I created. There are people continuing that work on GitHub.

**Comment by dveeden** [comment]
Looks like DBD::MariaDB is missing.
cc @pali

**Comment by dveeden** [comment]
I think all of the issues listed here have been fixed now
